### ISSUE TITLE
BUG Include all states when all leaves in the navigation comes visible when a filter is selected

### ISSUE THREAD

**Issue by Ta1Nur** [City-of-Helsinki/helerm-ui#175]
New feature works only when state is  "approved"
Filter do not work at all for other states.
Should work also with other states.

Check https://github.com/City-of-Helsinki/helerm-ui/issues/138

**Comment by Ta1Nur** [comment]
Issue is only straight after login, works when navigation is fetched again and classification information is reloaded with other states.

**Comment by Ta1Nur** [comment]
Still one issue - 
1. Login
2. Select filter i.e. "Odottaa hyväksyntää"
3. Filter works
4. Clear selected filter
5. Select filter i.e. "Hyväksytty"
6. Filter result empty

**Comment by vaaralav** [comment]
@Ta1Nur I believe this happens because of the feature mentioned in Slack. If there's no functions where the latest version is approved, the filter "Hyväksytty" doesn't show anything.

Now the filter "Hyväksytty" showed a single result [07 01 02 Tietopalvelu](https://helerm.dev.hel.ninja/view-tos/d406d6b8233044539af200713c85db80) at steps 6 and 9.
